### ISSUE TITLE
feat/출력 수정

### ISSUE THREAD

**Issue by rlatkd** [Kosa-hyosung-1-3/internet-banking#59]
## Description
- 콘솔에 출력되는 형식 퍼블리싱

## Todo
- [x] %%이니셜%%
- [x] %%고객%%
- [x] 회원가입, 로그인, 로그아웃
- [x] 내 계좌관리
- [x] 입출금
- [x] 계좌 이체
- [x] 거래 내역 조회: 개발 미구현
- [x] 고객 문의: 문의변경: 프린트 미완
- [x] 마이페이지
- [ ] %%관리자%%
- [ ] 로그인, 로그아웃
- [ ] 고객 계정 관리
- [ ] 고객 계좌 관리
- [ ] 고객 문의 관리
- [ ] 고객 이체 내역 관리
- [ ] 서브 관리자 등록

## ETC
